[build]
  publish = "."

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[redirects]]
  from = "/getsortedbeta"
  to = "https://testflight.apple.com/join/HyEvpM5S"
  status = 302
  force = true

[[redirects]]
  from = "/getsortedandroid"
  to = "https://play.google.com/apps/testing/com.brightcasa.getsorted"
  status = 302
  force = true
